import { PrismaClient, VehicleStatus, DriverStatus, OrderStatus, StopType } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedCentralBranchData() {
  console.log('🚀 Bắt đầu nạp dữ liệu vận tải phong phú cho Chi nhánh Miền Trung (BRANCH-DAD)...');

  // 1. Lấy chi nhánh Miền Trung
  const branchDAD = await prisma.branch.findUnique({
    where: { code: 'BRANCH-DAD' },
  });

  if (!branchDAD) {
    throw new Error('Không tìm thấy Chi nhánh Miền Trung (BRANCH-DAD) trong cơ sở dữ liệu!');
  }

  // 2. Tạo/Cập nhật các khách hàng doanh nghiệp đối tác tại Miền Trung
  const customers = [
    {
      code: 'CUST-VINAMILK',
      name: 'Công ty Cổ phần Sữa Việt Nam (Vinamilk)',
      taxCode: '0300588569',
      address: 'Số 10 Tân Trào, P. Tân Phú, Quận 7, TP. Hồ Chí Minh',
      contactPerson: 'Chị Mai Lan',
      phone: '028.5415.5555',
      email: 'logistics@vinamilk.com.vn',
    },
    {
      code: 'CUST-SUNHOUSE',
      name: 'Tập đoàn Sunhouse Việt Nam',
      taxCode: '0101659783',
      address: '35 Mạc Thái Tổ, Yên Hòa, Cầu Giấy, Hà Nội',
      contactPerson: 'Anh Trần Hùng',
      phone: '024.3736.6676',
      email: 'vanchuyen@sunhouse.com.vn',
    },
    {
      code: 'CUST-PANASONIC',
      name: 'Công ty TNHH Panasonic Việt Nam',
      taxCode: '0101375327',
      address: 'KCN Thăng Long, Đông Anh, Hà Nội',
      contactPerson: 'Anh Quang Minh',
      phone: '024.3955.0111',
      email: 'supplychain@vn.panasonic.com',
    },
    {
      code: 'CUST-THACO-CHULAI',
      name: 'Tập đoàn Ô tô Chu Lai - Trường Hải (Thaco Chu Lai)',
      taxCode: '4000381489',
      address: 'Khu công nghiệp cơ khí và ô tô Chu Lai - Trường Hải, Xã Tam Hiệp, Núi Thành, Quảng Nam',
      contactPerson: 'Anh Nguyễn Đình Hiếu (Điều vận Thaco)',
      phone: '0235.3567.168',
      email: 'logistics.chulai@thaco.com.vn',
    },
    {
      code: 'CUST-HOAPHAT-DUNGQUAT',
      name: 'Công ty Cổ phần Thép Hòa Phát Dung Quất',
      taxCode: '4300793234',
      address: 'Khu kinh tế Dung Quất, Xã Bình Đông, Huyện Bình Sơn, Quảng Ngãi',
      contactPerson: 'Kỹ sư Lê Văn Sang',
      phone: '0255.3626.888',
      email: 'vanchuyen@hoaphatdungquat.com.vn',
    },
    {
      code: 'CUST-SCAVI-HUE',
      name: 'Tổng Công ty Cổ phần May Scavi Huế',
      taxCode: '3300378912',
      address: 'Lô CN01, KCN Phong Điền, Thị trấn Phong Điền, Huyện Phong Điền, Thừa Thiên Huế',
      contactPerson: 'Chị Hoàng Thảo Nguyên',
      phone: '0234.3751.222',
      email: 'supply.chain@scavihue.vn',
    },
  ];

  const customerMap = new Map<string, string>();
  for (const c of customers) {
    const cust = await prisma.customer.upsert({
      where: { code: c.code },
      update: { name: c.name, address: c.address, phone: c.phone },
      create: c,
    });
    customerMap.set(c.code, cust.id);
  }
  console.log(`✅ Đã đồng bộ ${customers.length} khách hàng đối tác.`);

  // 3. Bổ sung Đội xe tải cho chi nhánh Miền Trung (nhiều phân khúc tải trọng & kích thước lọt lòng)
  const additionalVehicles = [
    {
      plateNumber: '43C-189.24',
      model: 'Hyundai New Mighty 110XL',
      vehicleType: 'Xe tải 3.5 tấn (Thùng bạt liên tỉnh)',
      homeBranchId: branchDAD.id,
      payloadCapacityKg: 3500,
      volumeCapacityM3: 21.0,
      lengthCm: 530,
      widthCm: 210,
      heightCm: 200,
      fuelConsumptionLitersPer100Km: 14.5,
      loadFuelSurchargePercentAtFullPayload: 20,
      fixedOperatingCostPerTrip: 95000,
      status: VehicleStatus.AVAILABLE,
      currentLatitude: 16.0125,
      currentLongitude: 108.1874,
    },
    {
      plateNumber: '43C-245.78',
      model: 'Hino 500 Series FC9J',
      vehicleType: 'Xe tải 6 tấn (Thùng kín đường dài)',
      homeBranchId: branchDAD.id,
      payloadCapacityKg: 6200,
      volumeCapacityM3: 32.5,
      lengthCm: 670,
      widthCm: 225,
      heightCm: 215,
      fuelConsumptionLitersPer100Km: 19.0,
      loadFuelSurchargePercentAtFullPayload: 20,
      fixedOperatingCostPerTrip: 135000,
      status: VehicleStatus.AVAILABLE,
      currentLatitude: 16.0125,
      currentLongitude: 108.1874,
    },
    {
      plateNumber: '43C-556.12',
      model: 'Isuzu Forward NQR75ME4',
      vehicleType: 'Xe tải 5 tấn (Thùng mui bạt)',
      homeBranchId: branchDAD.id,
      payloadCapacityKg: 5100,
      volumeCapacityM3: 26.5,
      lengthCm: 620,
      widthCm: 215,
      heightCm: 205,
      fuelConsumptionLitersPer100Km: 16.5,
      loadFuelSurchargePercentAtFullPayload: 20,
      fixedOperatingCostPerTrip: 115000,
      status: VehicleStatus.AVAILABLE,
      currentLatitude: 16.0125,
      currentLongitude: 108.1874,
    },
    {
      plateNumber: '43C-789.01',
      model: 'Kia Frontier K250',
      vehicleType: 'Xe tải 2.4 tấn (Thùng kín linh hoạt nội đô)',
      homeBranchId: branchDAD.id,
      payloadCapacityKg: 2400,
      volumeCapacityM3: 14.8,
      lengthCm: 440,
      widthCm: 190,
      heightCm: 185,
      fuelConsumptionLitersPer100Km: 11.5,
      loadFuelSurchargePercentAtFullPayload: 20,
      fixedOperatingCostPerTrip: 75000,
      status: VehicleStatus.AVAILABLE,
      currentLatitude: 16.0125,
      currentLongitude: 108.1874,
    },
    {
      plateNumber: '43H-012.89',
      model: 'Chenglong 3 chân M3 6x2',
      vehicleType: 'Xe tải nặng 9.8 tấn (Thùng bạt siêu dài)',
      homeBranchId: branchDAD.id,
      payloadCapacityKg: 9800,
      volumeCapacityM3: 53.0,
      lengthCm: 950,
      widthCm: 238,
      heightCm: 235,
      fuelConsumptionLitersPer100Km: 26.0,
      loadFuelSurchargePercentAtFullPayload: 20,
      fixedOperatingCostPerTrip: 190000,
      status: VehicleStatus.AVAILABLE,
      currentLatitude: 16.0125,
      currentLongitude: 108.1874,
    },
  ];

  for (const v of additionalVehicles) {
    await prisma.vehicle.upsert({
      where: { plateNumber: v.plateNumber },
      update: {
        homeBranchId: v.homeBranchId,
        status: v.status,
        payloadCapacityKg: v.payloadCapacityKg,
        volumeCapacityM3: v.volumeCapacityM3,
        lengthCm: v.lengthCm,
        widthCm: v.widthCm,
        heightCm: v.heightCm,
      },
      create: v,
    });
  }
  console.log(`✅ Đã bổ sung ${additionalVehicles.length} xe tải vào đội xe Chi nhánh Miền Trung.`);

  // 4. Bổ sung Đội ngũ Tài xế cho chi nhánh Miền Trung
  const additionalDrivers = [
    {
      fullName: 'Trần Văn Hùng',
      citizenId: '048089012345',
      phone: '0983112233',
      licenseNumber: 'C-48012345',
      licenseClass: 'C',
      licenseExpiry: new Date('2029-07-15'),
      homeBranchId: branchDAD.id,
      status: DriverStatus.AVAILABLE,
      fixedSalaryMonthly: 12500000,
      tripBasePay: 180000,
      perKmPay: 1300,
    },
    {
      fullName: 'Nguyễn Hữu Thắng',
      citizenId: '048091023456',
      phone: '0983223344',
      licenseNumber: 'C-48023456',
      licenseClass: 'C',
      licenseExpiry: new Date('2028-11-20'),
      homeBranchId: branchDAD.id,
      status: DriverStatus.AVAILABLE,
      fixedSalaryMonthly: 13000000,
      tripBasePay: 190000,
      perKmPay: 1350,
    },
    {
      fullName: 'Phan Đình Nam',
      citizenId: '048093034567',
      phone: '0983335566',
      licenseNumber: 'B2-48034567',
      licenseClass: 'B2',
      licenseExpiry: new Date('2030-03-10'),
      homeBranchId: branchDAD.id,
      status: DriverStatus.AVAILABLE,
      fixedSalaryMonthly: 9800000,
      tripBasePay: 120000,
      perKmPay: 950,
    },
    {
      fullName: 'Đỗ Thanh Bình',
      citizenId: '048087045678',
      phone: '0983446677',
      licenseNumber: 'C-48045678',
      licenseClass: 'C',
      licenseExpiry: new Date('2029-09-05'),
      homeBranchId: branchDAD.id,
      status: DriverStatus.AVAILABLE,
      fixedSalaryMonthly: 12000000,
      tripBasePay: 175000,
      perKmPay: 1250,
    },
    {
      fullName: 'Võ Quốc Huy',
      citizenId: '048084056789',
      phone: '0983557788',
      licenseNumber: 'FC-48056789',
      licenseClass: 'FC',
      licenseExpiry: new Date('2028-06-25'),
      homeBranchId: branchDAD.id,
      status: DriverStatus.AVAILABLE,
      fixedSalaryMonthly: 16500000,
      tripBasePay: 240000,
      perKmPay: 1600,
    },
  ];

  for (const d of additionalDrivers) {
    await prisma.driver.upsert({
      where: { citizenId: d.citizenId },
      update: {
        homeBranchId: d.homeBranchId,
        status: d.status,
        fixedSalaryMonthly: d.fixedSalaryMonthly,
        tripBasePay: d.tripBasePay,
        perKmPay: d.perKmPay,
      },
      create: d,
    });
  }
  console.log(`✅ Đã bổ sung ${additionalDrivers.length} tài xế trực ca cho Chi nhánh Miền Trung.`);

  // 5. Tạo chính xác 30 Đơn hàng Vận tải thực tế trải rộng toàn miền Trung
  // Quy chuẩn: Mỗi đơn chỉ có đúng 1 kiện vật lý (quantity: 1), đa dạng kích thước,
  // 100% kiện đều xếp vừa trong lòng xe tải.
  const centralOrders = [
    {
      orderNumber: 'ORD-DAD-001',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Hàng cơ khí ô tô: Cụm giảm xóc xe du lịch Kia nguyên kiện bọc màng co.',
      item: {
        sku: 'THACO-SUSP-01',
        description: 'Kiện cụm giảm xóc ô tô du lịch Kia',
        packageType: 'CRATE',
        lengthCm: 120,
        widthCm: 80,
        heightCm: 60,
        weightKg: 210,
      },
      pickup: {
        address: 'Nhà máy Sản xuất Xe Du lịch Thaco Kia, KCN Chu Lai, Xã Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Thủ kho Thaco - Anh Hiếu',
        contactPhone: '0905123451',
        windowStart: '2026-09-11T01:00:00Z', // 08:00 VN
        windowEnd: '2026-09-11T03:30:00Z',   // 10:30 VN
      },
      delivery: {
        address: 'Showroom Thaco Auto Đà Nẵng, 405 Tôn Đức Thắng, Hòa Minh, Liên Chiểu, Đà Nẵng',
        latitude: 16.0582,
        longitude: 108.1634,
        contactName: 'Bộ phận Phụ tùng - Anh Hùng',
        contactPhone: '0915123451',
        windowStart: '2026-09-11T06:30:00Z', // 13:30 VN
        windowEnd: '2026-09-11T09:30:00Z',   // 16:30 VN
      },
    },
    {
      orderNumber: 'ORD-DAD-002',
      customerCode: 'CUST-HOAPHAT-DUNGQUAT',
      notes: 'Thép cuộn công nghiệp rút nguội, xếp cẩn thận, cố định chêm gỗ chống lăn.',
      item: {
        sku: 'HP-WIRE-COIL',
        description: 'Thùng cuộn dây thép rút cường độ cao',
        packageType: 'PALLET',
        lengthCm: 110,
        widthCm: 110,
        heightCm: 85,
        weightKg: 580,
      },
      pickup: {
        address: 'Khu Liên hợp Gang thép Hòa Phát Dung Quất, Xã Bình Đông, Bình Sơn, Quảng Ngãi',
        latitude: 15.3312,
        longitude: 108.8456,
        contactName: 'Kho Thép Hòa Phát - Kỹ sư Sang',
        contactPhone: '0905123452',
        windowStart: '2026-09-11T00:30:00Z', // 07:30 VN
        windowEnd: '2026-09-11T03:00:00Z',   // 10:00 VN
      },
      delivery: {
        address: 'Xưởng Cơ khí Chế tạo Hòa Cầm, Đường số 5, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0145,
        longitude: 108.1892,
        contactName: 'Quản đốc Xưởng Cơ khí - Anh Nam',
        contactPhone: '0915123452',
        windowStart: '2026-09-11T07:00:00Z', // 14:00 VN
        windowEnd: '2026-09-11T10:30:00Z',   // 17:30 VN
      },
    },
    {
      orderNumber: 'ORD-DAD-003',
      customerCode: 'CUST-SCAVI-HUE',
      notes: 'Phụ liệu may mặc cao cấp xuất khẩu EU, chống ẩm tuyệt đối.',
      item: {
        sku: 'SCAVI-FABRIC-EXP',
        description: 'Kiện phụ liệu may mặc và ren cao cấp xuất khẩu',
        packageType: 'CARTON',
        lengthCm: 140,
        widthCm: 90,
        heightCm: 70,
        weightKg: 180,
      },
      pickup: {
        address: 'Nhà máy Scavi Huế, Lô CN01, KCN Phong Điền, Phong Thu, Phong Điền, Thừa Thiên Huế',
        latitude: 16.5872,
        longitude: 107.3054,
        contactName: 'Kho Phụ liệu Scavi - Chị Nguyên',
        contactPhone: '0905123453',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Cảng Tiên Sa Đà Nẵng, 01 Yết Kiêu, Thọ Quang, Sơn Trà, Đà Nẵng',
        latitude: 16.1264,
        longitude: 108.2198,
        contactName: 'Kho CFS Cảng Tiên Sa - Anh Hải',
        contactPhone: '0915123453',
        windowStart: '2026-09-11T07:30:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-004',
      customerCode: 'CUST-VINAMILK',
      notes: 'Sữa tươi tiệt trùng đóng pallet, giữ nhiệt độ mát, không va đập.',
      item: {
        sku: 'VNM-DAD-MILK',
        description: 'Pallet sữa tươi tiệt trùng 100% Organic Đà Nẵng',
        packageType: 'PALLET',
        lengthCm: 120,
        widthCm: 100,
        heightCm: 110,
        weightKg: 650,
      },
      pickup: {
        address: 'Kho Vận Miền Trung Vinamilk, Đường số 2, KCN Hòa Khánh, Liên Chiểu, Đà Nẵng',
        latitude: 16.0735,
        longitude: 108.1482,
        contactName: 'Thủ kho Hòa Khánh - Chị Lan',
        contactPhone: '0905123454',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Trung tâm Phân phối Vinamilk Tam Kỳ, 128 Phan Bội Châu, Tân Thạnh, Tam Kỳ, Quảng Nam',
        latitude: 15.5678,
        longitude: 108.4821,
        contactName: 'Nhận hàng Tam Kỳ - Anh Phúc',
        contactPhone: '0915123454',
        windowStart: '2026-09-11T06:00:00Z',
        windowEnd: '2026-09-11T09:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-005',
      customerCode: 'CUST-PANASONIC',
      notes: 'Tủ bảo quản đông lạnh công nghiệp nhà hàng/resort, hàng giá trị cao.',
      item: {
        sku: 'PANA-FREEZER-IND',
        description: 'Tủ bảo quản lạnh công nghiệp Panasonic',
        packageType: 'CRATE',
        lengthCm: 160,
        widthCm: 85,
        heightCm: 125,
        weightKg: 340,
      },
      pickup: {
        address: 'Trung tâm Phân phối Panasonic Đà Nẵng, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Kho Panasonic - Anh Minh',
        contactPhone: '0905123455',
        windowStart: '2026-09-11T02:00:00Z',
        windowEnd: '2026-09-11T04:30:00Z',
      },
      delivery: {
        address: 'Khách sạn Resort Lăng Cô, Thị trấn Lăng Cô, Phú Lộc, Thừa Thiên Huế',
        latitude: 16.2305,
        longitude: 108.0815,
        contactName: 'Bếp trưởng Resort - Anh Tuấn',
        contactPhone: '0915123455',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-006',
      customerCode: 'CUST-SUNHOUSE',
      notes: 'Máy lọc nước RO công nghiệp cho chuỗi siêu thị gia dụng.',
      item: {
        sku: 'SH-WATER-RO-10',
        description: 'Thùng máy lọc nước RO công nghiệp Sunhouse',
        packageType: 'CARTON',
        lengthCm: 95,
        widthCm: 65,
        heightCm: 115,
        weightKg: 120,
      },
      pickup: {
        address: 'Tổng kho Sunhouse Miền Trung, 52 Nguyễn Thị Định, An Hải Bắc, Sơn Trà, Đà Nẵng',
        latitude: 16.0789,
        longitude: 108.2345,
        contactName: 'Kho Sunhouse Sơn Trà - Anh Hoàng',
        contactPhone: '0905123456',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Siêu thị Điện máy Chợ Lớn Hội An, 245 Lý Thường Kiệt, Cẩm Phô, Hội An, Quảng Nam',
        latitude: 15.8801,
        longitude: 108.3380,
        contactName: 'Thủ kho Chợ Lớn Hội An - Chị Trâm',
        contactPhone: '0915123456',
        windowStart: '2026-09-11T04:00:00Z',
        windowEnd: '2026-09-11T07:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-007',
      customerCode: 'CUST-HOAPHAT-DUNGQUAT',
      notes: 'Thiết bị phụ tùng lò luyện kim nhập khẩu từ cảng biển về nhà máy Dung Quất.',
      item: {
        sku: 'HP-REFRACTORY-PT',
        description: 'Kiện phụ tùng lò cao luyện thép chịu nhiệt',
        packageType: 'CRATE',
        lengthCm: 150,
        widthCm: 95,
        heightCm: 80,
        weightKg: 520,
      },
      pickup: {
        address: 'Cảng Quốc tế Chân Mây, Xã Lộc Vĩnh, Phú Lộc, Thừa Thiên Huế',
        latitude: 16.3298,
        longitude: 107.9892,
        contactName: 'Cảng vụ Chân Mây - Anh Cường',
        contactPhone: '0905123457',
        windowStart: '2026-09-11T00:30:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Ban Quản lý Nhà máy Hòa Phát, KCN Dung Quất, Bình Đông, Bình Sơn, Quảng Ngãi',
        latitude: 15.3421,
        longitude: 108.8214,
        contactName: 'Phòng Cơ điện Hòa Phát - Anh Việt',
        contactPhone: '0915123457',
        windowStart: '2026-09-11T07:30:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-008',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Khung sườn kim loại dài, yêu cầu xe sàn phẳng có dây tăng đơ ràng buộc.',
      item: {
        sku: 'THACO-FRAME-PART',
        description: 'Kiện khung sườn phụ xe buýt Thaco TB120',
        packageType: 'CRATE',
        lengthCm: 220,
        widthCm: 120,
        heightCm: 110,
        weightKg: 780,
      },
      pickup: {
        address: 'Nhà máy Cơ khí Chế tạo Thaco Chu Lai, Xã Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Điều phối Thaco Cơ khí - Anh Bình',
        contactPhone: '0905123458',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Xí nghiệp Đầu máy Toa xe Đà Nẵng, 02 Hải Phòng, Tam Thuận, Thanh Khê, Đà Nẵng',
        latitude: 16.0689,
        longitude: 108.2045,
        contactName: 'Tổ Tiếp nhận Cơ khí Đường sắt - Anh Dũng',
        contactPhone: '0915123458',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-009',
      customerCode: 'CUST-SCAVI-HUE',
      notes: 'Cuộn vải bạt công nghiệp chuyên dụng, không dính dầu mỡ trên sàn xe.',
      item: {
        sku: 'SCAVI-ROLL-TEX',
        description: 'Thùng nguyên liệu vải cuộn chống thấm xuất khẩu',
        packageType: 'CARTON',
        lengthCm: 180,
        widthCm: 60,
        heightCm: 60,
        weightKg: 190,
      },
      pickup: {
        address: 'Kho vải nguyên liệu Scavi, KCN Phú Bài, Hương Thủy, Thừa Thiên Huế',
        latitude: 16.3985,
        longitude: 107.6978,
        contactName: 'Kho Phú Bài - Anh Bảo',
        contactPhone: '0905123459',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Xưởng May May Mặc Hòa Thọ, 36 Ông Ích Đường, Hòa Thọ Đông, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0215,
        longitude: 108.2012,
        contactName: 'KCS Hòa Thọ - Chị Mai',
        contactPhone: '0915123459',
        windowStart: '2026-09-11T06:00:00Z',
        windowEnd: '2026-09-11T08:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-010',
      customerCode: 'CUST-PANASONIC',
      notes: 'Cụm dàn nóng điều hòa trung tâm cho khách sạn 5 sao tại Huế.',
      item: {
        sku: 'PANA-MULTI-AC',
        description: 'Kiện hệ thống điều hòa Multi Panasonic inverter',
        packageType: 'CRATE',
        lengthCm: 130,
        widthCm: 90,
        heightCm: 95,
        weightKg: 230,
      },
      pickup: {
        address: 'Trung tâm Phân phối Panasonic Đà Nẵng, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Kho Panasonic - Anh Quang',
        contactPhone: '0905123460',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Dự án Tòa nhà Khách sạn Imperial Huế, 08 Hùng Vương, Phú Hội, TP. Huế',
        latitude: 16.4637,
        longitude: 107.5909,
        contactName: 'Kỹ sư Cơ điện Imperial - Anh Long',
        contactPhone: '0915123460',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-011',
      customerCode: 'CUST-VINAMILK',
      notes: 'Thiết bị cảm biến đo lường và bồn mẫu vi sinh phòng thí nghiệm.',
      item: {
        sku: 'VNM-LAB-VESSEL',
        description: 'Kiện bồn chứa vi sinh mẫu kiểm nghiệm sữa',
        packageType: 'CRATE',
        lengthCm: 90,
        widthCm: 90,
        heightCm: 110,
        weightKg: 140,
      },
      pickup: {
        address: 'Trung tâm Kiểm nghiệm Đo lường Chất lượng 2, 97 Lý Tự Trọng, Hải Châu, Đà Nẵng',
        latitude: 16.0745,
        longitude: 108.2212,
        contactName: 'Phòng Thí nghiệm Quatest 2 - Chị An',
        contactPhone: '0905123461',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Trang trại Bò sữa Vinamilk Quảng Ngãi, Đức Phú, Mộ Đức, Quảng Ngãi',
        latitude: 14.9823,
        longitude: 108.8745,
        contactName: 'Trưởng trạm Kỹ thuật - Anh Nam',
        contactPhone: '0915123461',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-012',
      customerCode: 'CUST-SUNHOUSE',
      notes: 'Lô bếp điện từ Sunhouse Mama giao siêu thị điện máy Quảng Ngãi.',
      item: {
        sku: 'SH-INDUCT-PALLET',
        description: 'Pallet bếp từ đôi hồng ngoại cao cấp Sunhouse',
        packageType: 'PALLET',
        lengthCm: 120,
        widthCm: 80,
        heightCm: 85,
        weightKg: 280,
      },
      pickup: {
        address: 'Tổng kho Sunhouse Đà Nẵng, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Thủ kho Sunhouse - Anh Sơn',
        contactPhone: '0905123462',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Siêu thị Điện máy Xanh TP. Quảng Ngãi, 350 Quang Trung, TP. Quảng Ngãi',
        latitude: 15.1205,
        longitude: 108.8045,
        contactName: 'Quản lý Kho ĐMX Quảng Ngãi - Anh Đạt',
        contactPhone: '0915123462',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-013',
      customerCode: 'CUST-HOAPHAT-DUNGQUAT',
      notes: 'Máy bơm thủy lực áp suất cao cho hệ thống đúc liên tục.',
      item: {
        sku: 'HP-HYDR-PUMP',
        description: 'Kiện phụ tùng bơm thủy lực cao áp Komatsu',
        packageType: 'CRATE',
        lengthCm: 100,
        widthCm: 75,
        heightCm: 70,
        weightKg: 310,
      },
      pickup: {
        address: 'Cảng Quốc tế Chu Lai, Xã Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4654,
        longitude: 108.7189,
        contactName: 'Cảng Chu Lai Logistics - Anh Tuấn',
        contactPhone: '0905123463',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Phân xưởng Cán thép Hòa Phát, KCN Dung Quất, Bình Sơn, Quảng Ngãi',
        latitude: 15.3312,
        longitude: 108.8456,
        contactName: 'Nhận hàng Cơ điện Hòa Phát - Anh Toàn',
        contactPhone: '0915123463',
        windowStart: '2026-09-11T04:30:00Z',
        windowEnd: '2026-09-11T07:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-014',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Kính xe tải chuyên dụng có khung gỗ bảo vệ, nghiêm cấm va chạm mạnh.',
      item: {
        sku: 'THACO-WINDSHIELD',
        description: 'Kiện kính chắn gió ô tô tải Fuso chuyên dụng',
        packageType: 'CRATE',
        lengthCm: 190,
        widthCm: 110,
        heightCm: 40,
        weightKg: 160,
      },
      pickup: {
        address: 'Nhà máy Sản xuất Kính ô tô Thaco, KCN Chu Lai, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Kho Kính Thaco - Anh Khoa',
        contactPhone: '0905123464',
        windowStart: '2026-09-11T00:30:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Trung tâm Dịch vụ Bảo hành Thaco, 108 Hùng Vương, Phú Hội, TP. Huế',
        latitude: 16.4601,
        longitude: 107.5954,
        contactName: 'Trưởng xưởng Dịch vụ Thaco Huế - Anh Thịnh',
        contactPhone: '0915123464',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-015',
      customerCode: 'CUST-PANASONIC',
      notes: 'Khối aptomat công nghiệp trung thế cho trạm biến áp KCN Tam Thăng.',
      item: {
        sku: 'PANA-ACB-BREAKER',
        description: 'Thùng thiết bị đóng cắt tự động ACB trung thế',
        packageType: 'CRATE',
        lengthCm: 85,
        widthCm: 75,
        heightCm: 90,
        weightKg: 175,
      },
      pickup: {
        address: 'Trạm Kỹ thuật Điện lực Hòa Khánh, KCN Hòa Khánh, Liên Chiểu, Đà Nẵng',
        latitude: 16.0735,
        longitude: 108.1482,
        contactName: 'Kho Vật tư Điện lực - Anh Khải',
        contactPhone: '0905123465',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Nhà máy May Dệt Hòa Thọ Tam Kỳ, KCN Tam Thăng, TP. Tam Kỳ, Quảng Nam',
        latitude: 15.5923,
        longitude: 108.5342,
        contactName: 'Kỹ sư Trưởng Cơ điện Tam Kỳ - Anh Nghĩa',
        contactPhone: '0915123465',
        windowStart: '2026-09-11T06:00:00Z',
        windowEnd: '2026-09-11T08:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-016',
      customerCode: 'CUST-VINAMILK',
      notes: 'Máy in hạn sử dụng chính xác cao dùng trong dây chuyền chiết rót.',
      item: {
        sku: 'VNM-LASER-CODER',
        description: 'Kiện máy in hạn sử dụng Laser công nghiệp',
        packageType: 'CRATE',
        lengthCm: 70,
        widthCm: 60,
        heightCm: 80,
        weightKg: 85,
      },
      pickup: {
        address: 'Trung tâm Dịch vụ Thiết bị Markem, 15 Quang Trung, Hải Châu, Đà Nẵng',
        latitude: 16.0721,
        longitude: 108.2201,
        contactName: 'Văn phòng Kỹ thuật Markem - Chị Ly',
        contactPhone: '0905123466',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Nhà máy Chế biến Thực phẩm Quảng Ngãi, KCN Tịnh Phong, Sơn Tịnh, Quảng Ngãi',
        latitude: 15.2156,
        longitude: 108.7845,
        contactName: 'Tổ Bảo trì Dây chuyền - Anh Hậu',
        contactPhone: '0915123466',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-017',
      customerCode: 'CUST-SUNHOUSE',
      notes: 'Hàng gia dụng điện cao cấp giao đại lý phân phối Đông Hà Quảng Trị.',
      item: {
        sku: 'SH-AIR-FRYER-15L',
        description: 'Kiện nồi chiên không dầu công suất lớn Sunhouse',
        packageType: 'CARTON',
        lengthCm: 80,
        widthCm: 60,
        heightCm: 65,
        weightKg: 95,
      },
      pickup: {
        address: 'Tổng kho Sunhouse Đà Nẵng, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Thủ kho Sunhouse - Anh Sơn',
        contactPhone: '0905123467',
        windowStart: '2026-09-11T00:30:00Z',
        windowEnd: '2026-09-11T02:30:00Z',
      },
      delivery: {
        address: 'Cửa hàng Điện máy Đông Hà, 82 Lê Duẩn, TP. Đông Hà, Quảng Trị',
        latitude: 16.8123,
        longitude: 107.1045,
        contactName: 'Chủ đại lý Đông Hà - Chị Nguyệt',
        contactPhone: '0915123467',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-018',
      customerCode: 'CUST-SCAVI-HUE',
      notes: 'Máy may công nghiệp vi tính tự động nhập khẩu từ Nhật Bản.',
      item: {
        sku: 'SCAVI-SEW-BROTHER',
        description: 'Kiện máy may lập trình vi tính Brother cao cấp',
        packageType: 'CRATE',
        lengthCm: 110,
        widthCm: 85,
        heightCm: 90,
        weightKg: 165,
      },
      pickup: {
        address: 'Cảng Tiên Sa Đà Nẵng, Thọ Quang, Sơn Trà, Đà Nẵng',
        latitude: 16.1264,
        longitude: 108.2198,
        contactName: 'Đại lý Giao nhận Hàng hải - Anh Quân',
        contactPhone: '0905123468',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Xưởng May Scavi Phong Điền, KCN Phong Điền, Huyện Phong Điền, Thừa Thiên Huế',
        latitude: 16.5872,
        longitude: 107.3054,
        contactName: 'Xưởng trưởng Scavi Phong Điền - Anh Kiệt',
        contactPhone: '0915123468',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-019',
      customerCode: 'CUST-HOAPHAT-DUNGQUAT',
      notes: 'Hàng pallet bột trợ dung quặng sắt tinh khiết, đóng bao kín chống ẩm.',
      item: {
        sku: 'HP-FLUX-BATCH',
        description: 'Thùng phụ gia trợ dung luyện cán thép hạt mịn',
        packageType: 'PALLET',
        lengthCm: 100,
        widthCm: 100,
        heightCm: 90,
        weightKg: 680,
      },
      pickup: {
        address: 'Cảng Liên Chiểu (Khu vực tiếp nhận hàng bách hóa), Liên Chiểu, Đà Nẵng',
        latitude: 16.1189,
        longitude: 108.1345,
        contactName: 'Đội Tiếp nhận Liên Chiểu - Anh Lực',
        contactPhone: '0905123469',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Tổng kho Nguyên liệu Hòa Phát, KCN Dung Quất, Bình Sơn, Quảng Ngãi',
        latitude: 15.3421,
        longitude: 108.8214,
        contactName: 'Kho Nguyên liệu Dung Quất - Anh Chiến',
        contactPhone: '0915123469',
        windowStart: '2026-09-11T07:30:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-020',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Bộ ghế bọc da nguyên chiếc chuyển giao đại lý Mazda Thừa Thiên Huế.',
      item: {
        sku: 'THACO-SEAT-SET',
        description: 'Kiện ghế ngồi bọc da cao cấp xe Mazda CX-5',
        packageType: 'CRATE',
        lengthCm: 150,
        widthCm: 95,
        heightCm: 110,
        weightKg: 240,
      },
      pickup: {
        address: 'Nhà máy Nội thất Xe Du lịch Thaco, KCN Chu Lai, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Thủ kho Nội thất Thaco - Anh Cảnh',
        contactPhone: '0905123470',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Showroom Mazda Thừa Thiên Huế, An Cựu City, Hoàng Quốc Việt, TP. Huế',
        latitude: 16.4498,
        longitude: 107.6045,
        contactName: 'Bộ phận Phụ tùng Mazda Huế - Anh Việt',
        contactPhone: '0915123470',
        windowStart: '2026-09-11T07:30:00Z',
        windowEnd: '2026-09-11T10:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-021',
      customerCode: 'CUST-PANASONIC',
      notes: 'Tấm pin năng lượng mặt trời công nghệ Nhật Bản cho nông nghiệp thông minh.',
      item: {
        sku: 'PANA-SOLAR-HIT',
        description: 'Kiện pin mặt trời Panasonic HIT hiệu suất cao',
        packageType: 'CRATE',
        lengthCm: 175,
        widthCm: 105,
        heightCm: 45,
        weightKg: 210,
      },
      pickup: {
        address: 'Kho Thiết bị Năng lượng, KCN Điện Nam - Điện Ngọc, Điện Bàn, Quảng Nam',
        latitude: 15.9234,
        longitude: 108.2612,
        contactName: 'Kho Năng lượng Điện Ngọc - Anh Vinh',
        contactPhone: '0905123471',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Trang trại Nông nghiệp Công nghệ cao Nam Phước, Huyện Duy Xuyên, Quảng Nam',
        latitude: 15.8345,
        longitude: 108.2456,
        contactName: 'Ban Quản lý Dự án Nông nghiệp - Anh Hạnh',
        contactPhone: '0915123471',
        windowStart: '2026-09-11T04:30:00Z',
        windowEnd: '2026-09-11T07:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-022',
      customerCode: 'CUST-VINAMILK',
      notes: 'Van tiết lưu Inox vi sinh chuyên dùng chế biến thực phẩm sạch.',
      item: {
        sku: 'VNM-SANITARY-VALVE',
        description: 'Kiện van tiết lưu và phụ kiện đường ống Inox vi sinh',
        packageType: 'CARTON',
        lengthCm: 65,
        widthCm: 50,
        heightCm: 40,
        weightKg: 55,
      },
      pickup: {
        address: 'Công ty Cơ khí Thiết bị Tân Long, 120 Điện Biên Phủ, Thanh Khê, Đà Nẵng',
        latitude: 16.0645,
        longitude: 108.1912,
        contactName: 'Kỹ sư Bán hàng Tân Long - Anh Danh',
        contactPhone: '0905123472',
        windowStart: '2026-09-11T02:00:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Chi nhánh Sữa Vinamilk Chu Lai, KCN Bắc Chu Lai, Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4412,
        longitude: 108.6734,
        contactName: 'Trưởng bộ phận Cơ điện Vinamilk - Anh Tân',
        contactPhone: '0915123472',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-023',
      customerCode: 'CUST-SUNHOUSE',
      notes: 'Lò vi sóng cao cấp phục vụ trung tâm mua sắm huyện Thăng Bình.',
      item: {
        sku: 'SH-MICROWAVE-G32',
        description: 'Thùng lò vi sóng kết hợp nướng Sunhouse',
        packageType: 'CARTON',
        lengthCm: 75,
        widthCm: 55,
        heightCm: 50,
        weightKg: 65,
      },
      pickup: {
        address: 'Kho Vận Miền Trung Sunhouse, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Thủ kho Sunhouse - Anh Sơn',
        contactPhone: '0905123473',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Siêu thị Điện máy Thăng Bình, Thị trấn Hà Lam, Thăng Bình, Quảng Nam',
        latitude: 15.6987,
        longitude: 108.3765,
        contactName: 'Cửa hàng trưởng Hà Lam - Chị Loan',
        contactPhone: '0915123473',
        windowStart: '2026-09-11T04:00:00Z',
        windowEnd: '2026-09-11T06:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-024',
      customerCode: 'CUST-SCAVI-HUE',
      notes: 'Máy ép nhãn nhiệt tự động từ cảng biển về nhà máy dệt may Tam Thăng.',
      item: {
        sku: 'SCAVI-HEAT-PRESS',
        description: 'Kiện máy ép nhiệt ép nhãn chuyển nhiệt tự động',
        packageType: 'CRATE',
        lengthCm: 90,
        widthCm: 70,
        heightCm: 85,
        weightKg: 130,
      },
      pickup: {
        address: 'Cảng Quốc tế Chân Mây, Phú Lộc, Thừa Thiên Huế',
        latitude: 16.3298,
        longitude: 107.9892,
        contactName: 'Kho Ngoại quan Chân Mây - Anh Tùng',
        contactPhone: '0905123474',
        windowStart: '2026-09-11T00:30:00Z',
        windowEnd: '2026-09-11T02:30:00Z',
      },
      delivery: {
        address: 'Nhà máy Dệt may Gia Định, KCN Tam Thăng, TP. Tam Kỳ, Quảng Nam',
        latitude: 15.5923,
        longitude: 108.5342,
        contactName: 'Kỹ sư Thiết bị May - Anh Quý',
        contactPhone: '0915123474',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-025',
      customerCode: 'CUST-HOAPHAT-DUNGQUAT',
      notes: 'Mẫu vật liệu thép tấm cường độ cao kiểm định phòng lab trường đại học.',
      item: {
        sku: 'HP-SAMPLE-SPEC',
        description: 'Kiện mẫu thử nghiệm cơ tính thép tấm cán nóng',
        packageType: 'CRATE',
        lengthCm: 50,
        widthCm: 40,
        heightCm: 30,
        weightKg: 48,
      },
      pickup: {
        address: 'Trung tâm Nghiên cứu Hòa Phát, KCN Dung Quất, Bình Sơn, Quảng Ngãi',
        latitude: 15.3421,
        longitude: 108.8214,
        contactName: 'Viện R&D Hòa Phát - Thạc sĩ Vũ',
        contactPhone: '0905123475',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:00:00Z',
      },
      delivery: {
        address: 'Viện Nghiên cứu Vật liệu - Trường ĐH Bách Khoa ĐN, 54 Nguyễn Lương Bằng, Liên Chiểu, Đà Nẵng',
        latitude: 16.0765,
        longitude: 108.1534,
        contactName: 'Trưởng Phòng Lab Vật liệu - TS. Huy',
        contactPhone: '0915123475',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-026',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Trục truyền động các-đăng xe tải trung nguyên pallet bảo vệ.',
      item: {
        sku: 'THACO-PROP-SHAFT',
        description: 'Pallet linh kiện trục các-đăng xe tải trung Thaco Ollin',
        packageType: 'PALLET',
        lengthCm: 160,
        widthCm: 80,
        heightCm: 60,
        weightKg: 380,
      },
      pickup: {
        address: 'Nhà máy Truyền động Thaco Chu Lai, Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Kho Truyền động Thaco - Anh Phát',
        contactPhone: '0905123476',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Trạm Đăng kiểm & Dịch vụ Kỹ thuật Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Trưởng xưởng Bảo hành - Anh Tiến',
        contactPhone: '0915123476',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-027',
      customerCode: 'CUST-PANASONIC',
      notes: 'Tủ phân phối điện công nghiệp phục vụ nhà máy dược phẩm tại VSIP Quảng Ngãi.',
      item: {
        sku: 'PANA-LOW-SWITCH',
        description: 'Tủ phân phối điện công nghiệp hạ thế Panasonic',
        packageType: 'CRATE',
        lengthCm: 140,
        widthCm: 80,
        heightCm: 130,
        weightKg: 360,
      },
      pickup: {
        address: 'Xưởng Thiết bị Tự động hóa, KCN Hòa Khánh, Liên Chiểu, Đà Nẵng',
        latitude: 16.0735,
        longitude: 108.1482,
        contactName: 'Quản đốc Tự động hóa - Anh Luận',
        contactPhone: '0905123477',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Dự án Nhà máy Dược phẩm Medochemie, KCN VSIP Quảng Ngãi, Tịnh Phong, Sơn Tịnh, Quảng Ngãi',
        latitude: 15.1789,
        longitude: 108.7965,
        contactName: 'Ban Chỉ huy Công trường - Kỹ sư Hưng',
        contactPhone: '0915123477',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-028',
      customerCode: 'CUST-VINAMILK',
      notes: 'Cảm biến vi điện tử nhạy cảm, bọc xốp bóng khí trong thùng carton gia cường.',
      item: {
        sku: 'VNM-FLOW-SENSOR',
        description: 'Thùng thiết bị cảm biến nhiệt độ & lưu lượng Endress+Hauser',
        packageType: 'CARTON',
        lengthCm: 45,
        widthCm: 35,
        heightCm: 30,
        weightKg: 35,
      },
      pickup: {
        address: 'Đại lý Thiết bị Đo lường Miền Trung, 88 Núi Thành, Hải Châu, Đà Nẵng',
        latitude: 16.0512,
        longitude: 108.2195,
        contactName: 'Kỹ thuật viên - Anh Trí',
        contactPhone: '0905123478',
        windowStart: '2026-09-11T00:30:00Z',
        windowEnd: '2026-09-11T02:30:00Z',
      },
      delivery: {
        address: 'Nhà máy Chế biến Nông sản Bích Chi, TT. Đức Phổ, Huyện Đức Phổ, Quảng Ngãi',
        latitude: 14.8089,
        longitude: 108.9567,
        contactName: 'Phòng Kỹ thuật Nhà máy - Anh Thuận',
        contactPhone: '0915123478',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-029',
      customerCode: 'CUST-SUNHOUSE',
      notes: 'Máy làm mát không khí công suất lớn trang bị hội nghị ven sông Hương Huế.',
      item: {
        sku: 'SH-AIR-COOL-COMM',
        description: 'Pallet máy làm mát không khí thương mại Sunhouse',
        packageType: 'PALLET',
        lengthCm: 130,
        widthCm: 90,
        heightCm: 120,
        weightKg: 195,
      },
      pickup: {
        address: 'Tổng kho Sunhouse Đà Nẵng, KCN Hòa Cầm, Cẩm Lệ, Đà Nẵng',
        latitude: 16.0125,
        longitude: 108.1874,
        contactName: 'Kho Sunhouse - Anh Sơn',
        contactPhone: '0905123479',
        windowStart: '2026-09-11T01:30:00Z',
        windowEnd: '2026-09-11T04:00:00Z',
      },
      delivery: {
        address: 'Trung tâm Hội nghị Khách sạn Century Riverside Huế, 49 Lê Lợi, Phú Hội, TP. Huế',
        latitude: 16.4678,
        longitude: 107.5912,
        contactName: 'Trưởng ban Tổ chức Sự kiện - Anh Tín',
        contactPhone: '0915123479',
        windowStart: '2026-09-11T07:00:00Z',
        windowEnd: '2026-09-11T10:00:00Z',
      },
    },
    {
      orderNumber: 'ORD-DAD-030',
      customerCode: 'CUST-THACO-CHULAI',
      notes: 'Khuôn dập chi tiết chính xác cao bằng hợp kim đúc nguyên khối.',
      item: {
        sku: 'THACO-DIE-MOLD',
        description: 'Kiện khuôn mẫu đúc chi tiết phụ tùng ô tô',
        packageType: 'CRATE',
        lengthCm: 120,
        widthCm: 110,
        heightCm: 95,
        weightKg: 720,
      },
      pickup: {
        address: 'Viện Khoa học Công nghệ và Chế tạo Máy Chu Lai, Tam Hiệp, Núi Thành, Quảng Nam',
        latitude: 15.4215,
        longitude: 108.6874,
        contactName: 'Viện Công nghệ Thaco - TS. Tùng',
        contactPhone: '0905123480',
        windowStart: '2026-09-11T01:00:00Z',
        windowEnd: '2026-09-11T03:30:00Z',
      },
      delivery: {
        address: 'Cảng Tiên Sa Đà Nẵng (Bãi xuất khẩu Container), Sơn Trà, Đà Nẵng',
        latitude: 16.1264,
        longitude: 108.2198,
        contactName: 'Ban Điều hành Cảng Container - Anh Lâm',
        contactPhone: '0915123480',
        windowStart: '2026-09-11T06:30:00Z',
        windowEnd: '2026-09-11T09:30:00Z',
      },
    },
  ];

  for (const o of centralOrders) {
    const custId = customerMap.get(o.customerCode);
    if (!custId) continue;

    const volM3 = Math.round(((o.item.lengthCm * o.item.widthCm * o.item.heightCm) / 1_000_000) * 1000) / 1000;

    const createdOrder = await prisma.order.upsert({
      where: { orderNumber: o.orderNumber },
      update: {
        branchId: branchDAD.id,
        customerId: custId,
        status: OrderStatus.CONFIRMED,
        totalWeightKg: o.item.weightKg,
        totalVolumeM3: volM3,
        totalPackages: 1,
        notes: o.notes,
      },
      create: {
        orderNumber: o.orderNumber,
        customerId: custId,
        branchId: branchDAD.id,
        status: OrderStatus.CONFIRMED,
        totalWeightKg: o.item.weightKg,
        totalVolumeM3: volM3,
        totalPackages: 1,
        notes: o.notes,
        items: {
          create: [
            {
              sku: o.item.sku,
              description: o.item.description,
              packageType: o.item.packageType,
              quantity: 1,
              weightKg: o.item.weightKg,
              lengthCm: o.item.lengthCm,
              widthCm: o.item.widthCm,
              heightCm: o.item.heightCm,
              volumeM3: volM3,
            },
          ],
        },
        stops: {
          create: [
            {
              type: StopType.PICKUP,
              sequence: 1,
              address: o.pickup.address,
              latitude: o.pickup.latitude,
              longitude: o.pickup.longitude,
              contactName: o.pickup.contactName,
              contactPhone: o.pickup.contactPhone,
              serviceDurationMinutes: 25,
              windowStart: new Date(o.pickup.windowStart),
              windowEnd: new Date(o.pickup.windowEnd),
            },
            {
              type: StopType.DELIVERY,
              sequence: 2,
              address: o.delivery.address,
              latitude: o.delivery.latitude,
              longitude: o.delivery.longitude,
              contactName: o.delivery.contactName,
              contactPhone: o.delivery.contactPhone,
              serviceDurationMinutes: 25,
              windowStart: new Date(o.delivery.windowStart),
              windowEnd: new Date(o.delivery.windowEnd),
            },
          ],
        },
      },
    });

    // Đồng bộ lại items và stops nếu đơn đã tồn tại từ trước
    await prisma.orderItem.deleteMany({ where: { orderId: createdOrder.id } });
    await prisma.orderItem.create({
      data: {
        orderId: createdOrder.id,
        sku: o.item.sku,
        description: o.item.description,
        packageType: o.item.packageType,
        quantity: 1,
        weightKg: o.item.weightKg,
        lengthCm: o.item.lengthCm,
        widthCm: o.item.widthCm,
        heightCm: o.item.heightCm,
        volumeM3: volM3,
      },
    });

    await Promise.all([
      prisma.orderStop.upsert({
        where: { orderId_sequence: { orderId: createdOrder.id, sequence: 1 } },
        update: {
          address: o.pickup.address,
          latitude: o.pickup.latitude,
          longitude: o.pickup.longitude,
          contactName: o.pickup.contactName,
          contactPhone: o.pickup.contactPhone,
          serviceDurationMinutes: 25,
          windowStart: new Date(o.pickup.windowStart),
          windowEnd: new Date(o.pickup.windowEnd),
        },
        create: {
          orderId: createdOrder.id,
          type: StopType.PICKUP,
          sequence: 1,
          address: o.pickup.address,
          latitude: o.pickup.latitude,
          longitude: o.pickup.longitude,
          contactName: o.pickup.contactName,
          contactPhone: o.pickup.contactPhone,
          serviceDurationMinutes: 25,
          windowStart: new Date(o.pickup.windowStart),
          windowEnd: new Date(o.pickup.windowEnd),
        },
      }),
      prisma.orderStop.upsert({
        where: { orderId_sequence: { orderId: createdOrder.id, sequence: 2 } },
        update: {
          address: o.delivery.address,
          latitude: o.delivery.latitude,
          longitude: o.delivery.longitude,
          contactName: o.delivery.contactName,
          contactPhone: o.delivery.contactPhone,
          serviceDurationMinutes: 25,
          windowStart: new Date(o.delivery.windowStart),
          windowEnd: new Date(o.delivery.windowEnd),
        },
        create: {
          orderId: createdOrder.id,
          type: StopType.DELIVERY,
          sequence: 2,
          address: o.delivery.address,
          latitude: o.delivery.latitude,
          longitude: o.delivery.longitude,
          contactName: o.delivery.contactName,
          contactPhone: o.delivery.contactPhone,
          serviceDurationMinutes: 25,
          windowStart: new Date(o.delivery.windowStart),
          windowEnd: new Date(o.delivery.windowEnd),
        },
      }),
    ]);
  }

  console.log(`✅ Đã khởi tạo hoàn tất ${centralOrders.length} đơn hàng thực tế trải rộng cho Chi nhánh Miền Trung.`);
}

if (require.main === module) {
  seedCentralBranchData()
    .then(async () => {
      await prisma.$disconnect();
      console.log('🎉 NẠP DỮ LIỆU MIỀN TRUNG THÀNH CÔNG VÀO DATABASE!');
      process.exit(0);
    })
    .catch(async (e) => {
      console.error('❌ Lỗi nạp dữ liệu miền Trung:', e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
